application :
    services :
        - service: &s1
            nom : service 1
            etats :
                - etat : &s1e1
                    nom : e1
                    nbJetons : 0
                - etat : &s1e2
                    nom : e2
                    nbJetons : 1
                - etat : &s1e3
                    nom : e3
                    nbJetons : 0
                - etat : &s1e4
                    nom : e4
                    nbJetons : 0
                - etat : &s1e5
                    nom : e5
                    nbJetons : 0
            transitions :
                - transition : &s1t1
                    nom : t1
                    etatsEntrants :
                        - etatEntrant : *s1e1
                    etatsSortants :
                        - etatSortant : *s1e2
                - transition : &s1t2
                    nom : t2
                    etatsEntrants :
                        - etatEntrant : *s1e2
                    etatsSortants :
                        - etatSortant : *s1e3
                - transition : &s1t3
                    nom : t3
                    etatsEntrants : 
                        - etatEntrant : *s1e2
                    etatsSortants:
                        - etatSortant : *s1e4
                - transition : &s1t4
                    nom : t4
                    etatsEntrants : 
                        - etatEntrant : *s1e3
                        - etatEntrant : *s1e4
                    etatsSortants :
                        - etatSortant : *s1e5
        